title: XUP Compute Acceleration Workshop
description:  These labs will provide hands-on experience using the Vitis unified software platform with Xilinx FPGA hardware.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky